mode: dev
telegram:
    token: 10887...
    api_id: 13...
    api_hash: 67bd...
    use_proxy: false
    proxy:
        type: MTProto
        host: ...
        port: ...
        secret: 3a19...
bot:
    phrases_path: 'slavkabot/phrases.txt'
    max_dialogs: 10
    cache_size: 10
    model:
        model_path: slavkabot/ChatBotAI/model_checkpoint
        length: 20